name: Build
on:
  push:
    branches:
      - unit-tests

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: clean install dependencies
        run: npm ci    
      
      - name: compile and create vsix
        run: npm run package -- -o torque-lsp.vsix

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: torque-lsp.vsix.zip
          path: ${{github.workspace}}/torque-lsp-*.vsix
